
import java.awt.Color;
import org.w3c.dom.css.RGBColor;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pubudu
 */
public class flag2 extends javax.swing.JFrame {

    /**
     * Creates new form flag2
     */
    public flag2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l11 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        l21 = new javax.swing.JLabel();
        l22 = new javax.swing.JLabel();
        l23 = new javax.swing.JLabel();
        l31 = new javax.swing.JLabel();
        l32 = new javax.swing.JLabel();
        l33 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pick A Country");
        getContentPane().setLayout(new java.awt.GridLayout(4, 3));

        l11.setBackground(new java.awt.Color(0, 0, 255));
        l11.setForeground(new java.awt.Color(0, 0, 255));
        l11.setOpaque(true);
        getContentPane().add(l11);

        l12.setBackground(new java.awt.Color(255, 255, 255));
        l12.setOpaque(true);
        getContentPane().add(l12);

        l13.setBackground(new java.awt.Color(255, 0, 0));
        l13.setOpaque(true);
        getContentPane().add(l13);

        l21.setBackground(new java.awt.Color(0, 0, 255));
        l21.setForeground(new java.awt.Color(0, 0, 255));
        l21.setOpaque(true);
        getContentPane().add(l21);

        l22.setBackground(new java.awt.Color(255, 255, 255));
        l22.setOpaque(true);
        getContentPane().add(l22);

        l23.setBackground(new java.awt.Color(255, 0, 0));
        l23.setOpaque(true);
        getContentPane().add(l23);

        l31.setBackground(new java.awt.Color(0, 0, 255));
        l31.setForeground(new java.awt.Color(0, 0, 255));
        l31.setOpaque(true);
        getContentPane().add(l31);

        l32.setBackground(new java.awt.Color(255, 255, 255));
        l32.setOpaque(true);
        getContentPane().add(l32);

        l33.setBackground(new java.awt.Color(255, 0, 0));
        l33.setOpaque(true);
        getContentPane().add(l33);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jButton1.setText("Bindia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setText("Argnta");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jButton2.setText("Hungery");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("France");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        getContentPane().add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jButton4.setText("Marjana");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Srilante");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        l11.setBackground(Color.orange);
        l12.setBackground(Color.orange);
        l13.setBackground(Color.orange);
        
        l21.setBackground(Color.white);
        l22.setBackground(Color.white);
        l23.setBackground(Color.white);
        
        l31.setBackground(Color.green);
        l32.setBackground(Color.green);
        l33.setBackground(Color.green);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        l11.setBackground(Color.getHSBColor(352, 0.7f, 0.65f));
        l12.setBackground(Color.getHSBColor(352, 0.7f, 0.65f));
        l13.setBackground(Color.getHSBColor(352, 0.7f, 0.65f));
        
        l21.setBackground(Color.white);
        l22.setBackground(Color.white);
        l23.setBackground(Color.white);
        
        l31.setBackground(Color.getHSBColor(1.39f, 0.8f,0.7f));
        l32.setBackground(Color.getHSBColor(1.39f, 0.8f,0.7f));
        l33.setBackground(Color.getHSBColor(1.39f, 0.8f,0.7f));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        l11.setBackground(Color.blue);
        l21.setBackground(Color.blue);
        l31.setBackground(Color.blue);
        
        l12.setBackground(Color.white);
        l22.setBackground(Color.white);
        l32.setBackground(Color.white);
        
        l13.setBackground(Color.red);
        l23.setBackground(Color.red);
        l33.setBackground(Color.red);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        l11.setBackground(Color.getHSBColor(1.74f, 0.7f, 0.65f));
        l12.setBackground(Color.getHSBColor(1.74f, 0.7f, 0.65f));
        l13.setBackground(Color.getHSBColor(1.74f, 0.7f, 0.65f));
        
        l21.setBackground(Color.yellow);
        l22.setBackground(Color.yellow);
        l23.setBackground(Color.yellow);
        
        l31.setBackground(Color.getHSBColor(1.39f, 0.8f,0.7f));
        l32.setBackground(Color.getHSBColor(1.39f, 0.8f,0.7f));
        l33.setBackground(Color.getHSBColor(1.39f, 0.8f,0.7f));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        l11.setBackground(Color.getHSBColor(0.1f, 0.9f,1f));
        l21.setBackground(Color.getHSBColor(0.1f, 0.9f,1f));
        l31.setBackground(Color.getHSBColor(0.1f, 0.9f,1f));
        
        l12.setBackground(Color.getHSBColor(1.39f, 0.8f,0.7f));
        l22.setBackground(Color.getHSBColor(1.39f, 0.8f,0.7f));
        l32.setBackground(Color.getHSBColor(1.39f, 0.8f,0.7f));
        
        l13.setBackground(Color.getHSBColor(352f, 0.7f, 0.65f));
        l23.setBackground(Color.getHSBColor(352f, 0.7f, 0.65f));
        l33.setBackground(Color.getHSBColor(352f, 0.7f, 0.65f));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        l11.setBackground(Color.CYAN);
        l21.setBackground(Color.CYAN);
        l31.setBackground(Color.cyan);
        
        l12.setBackground(Color.blue);
        l22.setBackground(Color.blue);
        l32.setBackground(Color.blue);
        
        l13.setBackground(Color.yellow);
        l23.setBackground(Color.yellow);
        l33.setBackground(Color.yellow);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(flag2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(flag2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(flag2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(flag2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new flag2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l21;
    private javax.swing.JLabel l22;
    private javax.swing.JLabel l23;
    private javax.swing.JLabel l31;
    private javax.swing.JLabel l32;
    private javax.swing.JLabel l33;
    // End of variables declaration//GEN-END:variables
}
